= Сервис Ассистент студента
:toc: macro
:toc-title:
:toclevels: 4
:icons: font

Авторы: Ковалев Павел, Богданов Егор, Петров Александр

toc::[]

== Описание проекта

Сервис Ассистент студента был разработан в рамках хакатона "Цифровой Санкт-Петербург". Этот сервис предназначен 
для студентов, чтобы помочь им в повседневных задачах и организации учебного процесса.

== Установка

Для установки и запуска сервиса Ассистент студента, следуйте инструкциям ниже:

1. Клонируйте репозиторий на свою локальную машину:
+
[source,sh]
----
git clone https://github.com/Pavel7004/assistant-student.git
----
2. Перейдите в директорию проекта:
+
[source,sh]
----
cd assistant-student
----
3. Установите зависимости, используя менеджер пакетов pip:
+
[source,sh]
----
pip install -r requirements.txt
----
4. Запустите сервис:
+
[source,sh]
----
python app.py
----

== Использование

Сервис Ассистент студента предоставляет следующие функции:

- Календарь: Просмотр расписания занятий и дедлайнов.
- Задачи: Создание и отслеживание задач.
- Управление файлами: Загрузка и хранение файлов, связанных с учебными материалами.
- Чат с преподавателем: Возможность общаться с преподавателями через встроенный чат.

Чтобы использовать сервис, откройте веб-браузер и перейдите по адресу http://localhost:5000.

== Вклад

Если вы хотите внести свой вклад в развитие проекта, вы можете сделать следующее:

- Создайте форк репозитория.
- Внесите необходимые изменения.
- Отправьте pull request.

Мы будем рады принять ваши предложения и улучшения!

== Лицензия

Сервис Ассистент студента распространяется под лицензией MIT. Подробную информацию можно найти в файле LICENSE.
