services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    hostname: "test_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: student_courses

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
